# Generated by Django 5.2 on 2025-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('ritual', models.BooleanField(default=False)),
                ('concentration', models.BooleanField(default=False)),
            ],
        ),
    ]
