# Generated by Django 5.2 on 2025-09-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=0)),
                ('ritual', models.BooleanField(default=False)),
                ('concentration', models.BooleanField(default=False)),
                ('components', models.JSONField(default=list)),
                ('casting_time', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
