# Generated by Django 5.2 on 2025-09-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='api_id',
        ),
        migrations.AlterField(
            model_name='spell',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
