# Generated by Django 5.2 on 2025-09-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_remove_spell_api_id_alter_spell_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='spell',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
