# Generated by Django 5.2 on 2025-09-04 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.PositiveIntegerField(default=10)),
                ('dexterity', models.PositiveIntegerField(default=10)),
                ('constitution', models.PositiveIntegerField(default=10)),
                ('intelligence', models.PositiveIntegerField(default=10)),
                ('wisdom', models.PositiveIntegerField(default=10)),
                ('charisma', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField()),
                ('character_class', models.CharField(choices=[('barbarian', 'Barbarian'), ('bard', 'Bard'), ('cleric', 'Cleric'), ('druid', 'Druid'), ('fighter', 'Fighter'), ('monk', 'Monk'), ('paladin', 'Paladin'), ('ranger', 'Ranger'), ('rogue', 'Rogue'), ('sorcerer', 'Sorcerer'), ('warlock', 'Warlock'), ('wizard', 'Wizard')], max_length=20)),
                ('race', models.CharField(choices=[('dragonborn', 'Dragonborn'), ('dwarf', 'Dwarf'), ('elf', 'Elf'), ('gnome', 'Gnome'), ('half_elf', 'Half-Elf'), ('halfling', 'Halfling'), ('half_orc', 'Half-Orc'), ('human', 'Human'), ('tiefling', 'Tiefling'), ('giff', 'Giff')], max_length=20)),
                ('subclass', models.CharField(blank=True, choices=[('barbarian_berserker', 'Path of the Berserker'), ('barbarian_totem_warrior', 'Path of the Totem Warrior'), ('bard_lore', 'College of Lore'), ('bard_valor', 'College of Valor'), ('cleric_knowledge_domain', 'Knowledge Domain'), ('cleric_life_domain', 'Life Domain'), ('cleric_light_domain', 'Light Domain'), ('cleric_nature_domain', 'Nature Domain'), ('cleric_tempest_domain', 'Tempest Domain'), ('cleric_trickery_domain', 'Trickery Domain'), ('cleric_war_domain', 'War Domain'), ('druid_land', 'Circle of the Land'), ('druid_moon', 'Circle of the Moon'), ('fighter_champion', 'Champion'), ('fighter_battle_master', 'Battle Master'), ('fighter_eldritch_knight', 'Eldritch Knight'), ('monk_open_hand', 'Way of the Open Hand'), ('monk_shadow', 'Way of Shadow'), ('monk_four_elements', 'Way of the Four Elements'), ('paladin_devotion', 'Oath of Devotion'), ('paladin_ancients', 'Oath of the Ancients'), ('paladin_vengeance', 'Oath of Vengeance'), ('ranger_hunter', 'Hunter'), ('ranger_beast_master', 'Beast Master'), ('rogue_thief', 'Thief'), ('rogue_assassin', 'Assassin'), ('rogue_arcane_trickster', 'Arcane Trickster'), ('sorcerer_draconic_bloodline', 'Draconic Bloodline'), ('sorcerer_wild_magic', 'Wild Magic'), ('warlock_archfey', 'The Archfey'), ('warlock_fiend', 'The Fiend'), ('warlock_great_old_one', 'The Great Old One'), ('wizard_abjuration', 'School of Abjuration'), ('wizard_conjuration', 'School of Conjuration'), ('wizard_divination', 'School of Divination'), ('wizard_enchantment', 'School of Enchantment'), ('wizard_evocation', 'School of Evocation'), ('wizard_illusion', 'School of Illusion'), ('wizard_necromancy', 'School of Necromancy'), ('wizard_transmutation', 'School of Transmutation')], max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.stats')),
            ],
        ),
    ]
