# Generated by Django 5.2 on 2025-09-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('spells', models.ManyToManyField(blank=True, to='spells.spell')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('possible_spells', models.ManyToManyField(blank=True, to='spells.spell')),
                ('subclasses', models.ManyToManyField(blank=True, to='character_structure.subclass')),
            ],
        ),
    ]
