# Generated by Django 5.2 on 2025-09-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_structure', '0001_initial'),
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubclassSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_granted', models.IntegerField()),
                ('always_prepared', models.BooleanField(default=True)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.spell')),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclass_spells', to='character_structure.subclass')),
            ],
            options={
                'unique_together': {('subclass', 'spell')},
            },
        ),
    ]
