# Generated by Django 5.2 on 2025-06-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_dnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('dm', 'Dungeon Master')], default='player', max_length=10),
        ),
    ]
